# Generated by Django 5.1.1 on 2024-11-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HTapp', '0002_habit_habitlog_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitlog',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.DeleteModel(
            name='HabitLog',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
